# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: controlplane.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "controlplane.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12\x63ontrolplane.proto\x12\x0c\x63ontrolplane\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto"\xcb\x01\n\x0cHealthStatus\x12\x31\n\x06status\x18\x01 \x01(\x0e\x32!.controlplane.HealthStatus.Status\x12\x0f\n\x07message\x18\x02 \x01(\t\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp"H\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\x12\x13\n\x0fSERVICE_UNKNOWN\x10\x03"F\n\nLogRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x0e\n\x06\x66ollow\x18\x02 \x01(\x08\x12\x12\n\ntail_lines\x18\x03 \x01(\x05"n\n\x07LogLine\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05level\x18\x03 \x01(\t\x12\x14\n\x0cservice_name\x18\x04 \x01(\t"O\n\rDeployRequest\x12\r\n\x05slugs\x18\x01 \x03(\t\x12\x16\n\x0ewait_for_ready\x18\x02 \x01(\x08\x12\x17\n\x0ftimeout_seconds\x18\x03 \x01(\x05"e\n\x0c\x44\x65ployResult\x12-\n\x08services\x18\x01 \x03(\x0b\x32\x1b.controlplane.ServiceResult\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t"\xb9\x01\n\rServiceResult\x12\x0c\n\x04slug\x18\x01 \x01(\t\x12\x14\n\x0cservice_name\x18\x02 \x01(\t\x12\x10\n\x08\x64\x65ployed\x18\x03 \x01(\x08\x12\x12\n\nimage_name\x18\x04 \x01(\t\x12\x14\n\x0c\x63ontainer_id\x18\x05 \x01(\t\x12\x31\n\rhealth_status\x18\x06 \x01(\x0b\x32\x1a.controlplane.HealthStatus\x12\x15\n\rerror_message\x18\x07 \x01(\t2\xd5\x01\n\x0c\x43ontrolPlane\x12\x41\n\x0bHealthCheck\x12\x16.google.protobuf.Empty\x1a\x1a.controlplane.HealthStatus\x12?\n\nStreamLogs\x12\x18.controlplane.LogRequest\x1a\x15.controlplane.LogLine0\x01\x12\x41\n\x06\x44\x65ploy\x12\x1b.controlplane.DeployRequest\x1a\x1a.controlplane.DeployResultb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "controlplane_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_HEALTHSTATUS"]._serialized_start = 99
    _globals["_HEALTHSTATUS"]._serialized_end = 302
    _globals["_HEALTHSTATUS_STATUS"]._serialized_start = 230
    _globals["_HEALTHSTATUS_STATUS"]._serialized_end = 302
    _globals["_LOGREQUEST"]._serialized_start = 304
    _globals["_LOGREQUEST"]._serialized_end = 374
    _globals["_LOGLINE"]._serialized_start = 376
    _globals["_LOGLINE"]._serialized_end = 486
    _globals["_DEPLOYREQUEST"]._serialized_start = 488
    _globals["_DEPLOYREQUEST"]._serialized_end = 567
    _globals["_DEPLOYRESULT"]._serialized_start = 569
    _globals["_DEPLOYRESULT"]._serialized_end = 670
    _globals["_SERVICERESULT"]._serialized_start = 673
    _globals["_SERVICERESULT"]._serialized_end = 858
    _globals["_CONTROLPLANE"]._serialized_start = 861
    _globals["_CONTROLPLANE"]._serialized_end = 1074
# @@protoc_insertion_point(module_scope)
