# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import controlplane_pb2 as controlplane__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = "1.74.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in controlplane_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ControlPlaneStub(object):
    """Control plane service for managing deployments"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
            "/controlplane.ControlPlane/HealthCheck",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=controlplane__pb2.HealthStatus.FromString,
            _registered_method=True,
        )
        self.StreamLogs = channel.unary_stream(
            "/controlplane.ControlPlane/StreamLogs",
            request_serializer=controlplane__pb2.LogRequest.SerializeToString,
            response_deserializer=controlplane__pb2.LogLine.FromString,
            _registered_method=True,
        )
        self.Deploy = channel.unary_unary(
            "/controlplane.ControlPlane/Deploy",
            request_serializer=controlplane__pb2.DeployRequest.SerializeToString,
            response_deserializer=controlplane__pb2.DeployResult.FromString,
            _registered_method=True,
        )


class ControlPlaneServicer(object):
    """Control plane service for managing deployments"""

    def HealthCheck(self, request, context):
        """Health check for services"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StreamLogs(self, request, context):
        """Stream logs from a service"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Deploy(self, request, context):
        """Deploy services from repository slugs"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ControlPlaneServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=controlplane__pb2.HealthStatus.SerializeToString,
        ),
        "StreamLogs": grpc.unary_stream_rpc_method_handler(
            servicer.StreamLogs,
            request_deserializer=controlplane__pb2.LogRequest.FromString,
            response_serializer=controlplane__pb2.LogLine.SerializeToString,
        ),
        "Deploy": grpc.unary_unary_rpc_method_handler(
            servicer.Deploy,
            request_deserializer=controlplane__pb2.DeployRequest.FromString,
            response_serializer=controlplane__pb2.DeployResult.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "controlplane.ControlPlane", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "controlplane.ControlPlane", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class ControlPlane(object):
    """Control plane service for managing deployments"""

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/controlplane.ControlPlane/HealthCheck",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            controlplane__pb2.HealthStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StreamLogs(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/controlplane.ControlPlane/StreamLogs",
            controlplane__pb2.LogRequest.SerializeToString,
            controlplane__pb2.LogLine.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Deploy(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/controlplane.ControlPlane/Deploy",
            controlplane__pb2.DeployRequest.SerializeToString,
            controlplane__pb2.DeployResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
